/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.
    
Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, KMDFSmbusCreateDevice)
#endif

NTSTATUS
KMDFSmbusCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();
    DbgPrint(LOG_PREFIX
        ": KMDFSmbusCreateDevice message: Entry\n");
#if BBB

    ///*
    // * Set device init IO type, device type, init attributes.
    // */
    //WdfDeviceInitSetIoType(DeviceInit, WdfDeviceIoDirect);
    //WdfDeviceInitSetCharacteristics(
    //    DeviceInit, FILE_CHARACTERISTIC_PNP_DEVICE, FALSE);
    //WDF_OBJECT_ATTRIBUTES_INIT(&deviceAttributes);
    //WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_EXTENSION);

    WDF_PNPPOWER_EVENT_CALLBACKS pnpPowerCallbacks = { 0 };

    /*
    * Initialize PnP-power callbacks, attributes and a context area
    * for the device object.
    */
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpPowerCallbacks);

    pnpPowerCallbacks.EvtDeviceD0Entry = KMDFSmbusEvtDeviceD0Entry;
    pnpPowerCallbacks.EvtDeviceD0Exit = KMDFSmbusEvtDeviceD0Exit;

    ///*
    // * These two callbacks set up and tear down hardware state,
    // * specifically that which only has to be done once.
    // */
    //pnpPowerCallbacks.EvtDevicePrepareHardware =
    //    KMDFSmbusEvtDevicePrepareHardware;
    //pnpPowerCallbacks.EvtDeviceReleaseHardware =
    //    KMDFSmbusEvtDeviceReleaseHardware;

    /*
     * Register the PnP Callbacks.
     */
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpPowerCallbacks);
    /*
     * Initialize Fdo Attributes.
     *
     * By opting for SynchronizationScopeDevice, we tell the framework to
     * synchronize callbacks events of all the objects directly associated
     * with the device. In this driver, we will associate queues and
     * and DpcForIsr. By doing that we don't have to worry about synchronizing
     * access to device-context by Io Events and DpcForIsr because they would
     * not concurrently ever. Framework will serialize them by using an
     * internal device-lock.(optional)
     */
    deviceAttributes.SynchronizationScope = WdfSynchronizationScopeDevice;
#else
    WDF_PNPPOWER_EVENT_CALLBACKS pnpPowerCallbacks = { 0 };

    /*
    * Initialize PnP-power callbacks, attributes and a context area
    * for the device object.
    */
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpPowerCallbacks);

    pnpPowerCallbacks.EvtDeviceD0Entry = KMDFSmbusEvtDeviceD0Entry;
    pnpPowerCallbacks.EvtDeviceD0Exit = KMDFSmbusEvtDeviceD0Exit;

    ///*
    // * These two callbacks set up and tear down hardware state,
    // * specifically that which only has to be done once.
    // */
    //pnpPowerCallbacks.EvtDevicePrepareHardware =
    //    KMDFSmbusEvtDevicePrepareHardware;
    //pnpPowerCallbacks.EvtDeviceReleaseHardware =
    //    KMDFSmbusEvtDeviceReleaseHardware;

    /*
     * Register the PnP Callbacks.
     */
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpPowerCallbacks);

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);
#endif



    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. DeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        deviceContext = DeviceGetContext(device);

        //
        // Initialize the context.
        //
        deviceContext->PrivateDeviceData = 0;

        //
        // Create a device interface so that applications can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface(
            device,
            &GUID_DEVINTERFACE_KMDFSmbus,
            NULL // ReferenceString
            );

        if (NT_SUCCESS(status)) {
            //
            // Initialize the I/O Package and any Queues
            //
            status = KMDFSmbusQueueInitialize(device);
        }
    }
    DbgPrint(LOG_PREFIX
        ": KMDFSmbusCreateDevice message: 0x%x\n",
        status);
    return status;
}

NTSTATUS
KMDFSmbusEvtDeviceD0Entry(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE PreviousState
)
{
    NTSTATUS status = STATUS_SUCCESS;
   /* PDEVICE_EXTENSION devExt = FilterDevGetExt(Device);
    UNREFERENCED_PARAMETER(PreviousState);*/
    DbgPrint(LOG_PREFIX
        ": KMDFSmbusEvtDeviceD0Entry message: Entry\n");
    return status;
}

NTSTATUS
KMDFSmbusEvtDeviceD0Exit(
    _In_ WDFDEVICE Device,
    _In_ WDF_POWER_DEVICE_STATE TargetState
)
{
    NTSTATUS status = STATUS_SUCCESS;
    DbgPrint(LOG_PREFIX
        ": KMDFSmbusEvtDeviceD0Exit message: Entry\n");
    return status;
}