/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.
    
Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, KMDFPnpDeviceDriverCreateDevice)
#pragma alloc_text (PAGE, PnpDeviceEvtDeviceD0Entry)
#pragma alloc_text (PAGE, PnpDeviceEvtDeviceD0Exit)
#pragma alloc_text (PAGE, PnpDeviceEvtDeviceContextCleanup)
#endif

NTSTATUS
KMDFPnpDeviceDriverCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
)
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDFDEVICE device;
    NTSTATUS status;
    WDF_PNPPOWER_EVENT_CALLBACKS pnpPowerCallbacks = { 0 };

    PAGED_CODE();
    //
    // Pnp Power event callbacks.
    //
    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpPowerCallbacks);
    //The Call method order of Power control
    pnpPowerCallbacks.EvtDeviceD0Entry = PnpDeviceEvtDeviceD0Entry;
    pnpPowerCallbacks.EvtDeviceD0Exit = PnpDeviceEvtDeviceD0Exit;
    /*
     * Register the PnP Callbacks.
     */
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpPowerCallbacks);

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);
    //
    // We will just register for cleanup notification because we have to
    // delete the control-device when the last instance of the device goes
    // away. If we don't delete, the driver wouldn't get unloaded automatically
    // by the PNP subsystem.
    //
    deviceAttributes.EvtCleanupCallback = PnpDeviceEvtDeviceContextCleanup;

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. PnpDeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        deviceContext = PnpDeviceGetContext(device);

        //
        // Initialize the context.
        //
        deviceContext->PrivateDeviceData = 0;
        //
        // Add this device to the HPBaseDriverDevice collection.
        //
        WdfWaitLockAcquire(DriverDeviceCollectionLock, NULL);
        //
        // WdfCollectionAdd takes a reference on the item object and removes
        // it when you call WdfCollectionRemove.
        //
        status = WdfCollectionAdd(DriverDeviceCollection, device);
        if (!NT_SUCCESS(status)) {
            KdPrint(("WdfCollectionAdd failed with status code 0x%x\n", status));
        }
        WdfWaitLockRelease(DriverDeviceCollectionLock);

        //
        // Create a control device
        //
        status = KMDFPnpDeviceDriverCreateControlDevice(device);
        if (!NT_SUCCESS(status)) {
            KdPrint(("FilterCreateControlDevice failed with status 0x%x\n",
                status));
            //
            // Let us not fail AddDevice just because we weren't able to create the
            // control device.
            //
            status = STATUS_SUCCESS;
        }
#if false
        //
        // Create a device interface so that applications can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface(
            device,
            &GUID_DEVINTERFACE_KMDFPnpDeviceDriver,
            NULL // ReferenceString
        );

        if (NT_SUCCESS(status)) {
            //
            // Initialize the I/O Package and any Queues
            //
            status = KMDFPnpDeviceDriverQueueInitialize(device);
        }
#endif
    }

    return status;
}
#pragma warning(push)
#pragma warning(disable:28118) // this callback will run at IRQL=PASSIVE_LEVEL
/**
 * @brief Used to configure device on D0 entry
 *
 * @param dev WDF device
 * @param previousState previous power state
 *
 * @return On success, the function returns STATUS_SUCCESS
 * On failure it passes the relevant error code to the caller.
 */
NTSTATUS
PnpDeviceEvtDeviceD0Entry(IN WDFDEVICE Device,
    IN WDF_POWER_DEVICE_STATE PreviousState)
{
    UNREFERENCED_PARAMETER(Device);
    UNREFERENCED_PARAMETER(PreviousState);

    PAGED_CODE();
    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%ws %!FUNC! Exit %!STATUS!", LOG_TITLE, PreviousState);
    KdPrint(("%ws HPDriverEvtDeviceD0Entry...Exit 0x%x\n", LOG_TITLE, PreviousState));
    return STATUS_SUCCESS;
}
/**
 * @brief Used to configure device on D0 exit
 *
 * @param Device WDF device
 * @param TargetState Target power state
 *
 * @return On success, the function returns STATUS_SUCCESS
 * On failure it passes the relevant error code to the caller.
 */
NTSTATUS
PnpDeviceEvtDeviceD0Exit(IN WDFDEVICE Device,
    IN WDF_POWER_DEVICE_STATE TargetState)
{
    UNREFERENCED_PARAMETER(Device);
    PAGED_CODE();
    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%ws %!FUNC! Status %!STATUS!", LOG_TITLE, TargetState);
    KdPrint(("%ws HPDriverEvtDeviceD0Exit...Status 0x%x\n", LOG_TITLE, TargetState));
    //Set watchdog status
    //SetWatchdogRegistry();
    return STATUS_SUCCESS;
}
_Use_decl_annotations_
VOID
PnpDeviceEvtDeviceContextCleanup(
    WDFOBJECT Device
)
/*++

Routine Description:

   EvtDeviceRemove event callback must perform any operations that are
   necessary before the specified device is removed. The framework calls
   the driver's EvtDeviceRemove callback when the PnP manager sends
   an IRP_MN_REMOVE_DEVICE request to the driver stack.

Arguments:

    Device - Handle to a framework device object.

Return Value:

    WDF status code

--*/
{
    ULONG   count;

    PAGED_CODE();

    WdfWaitLockAcquire(DriverDeviceCollectionLock, NULL);

    count = WdfCollectionGetCount(DriverDeviceCollection);

    if (count == 1)
    {
        //
        // We are the last instance. So let us delete the control-device
        // so that driver can unload when the FilterDevice is deleted.
        // We absolutely have to do the deletion of control device with
        // the collection lock acquired because we implicitly use this
        // lock to protect ControlDevice global variable. We need to make
        // sure another thread doesn't attempt to create while we are
        // deleting the device.
        // Need This for PASS SDV test
        //
        KMDFPnpDeviceDriverDeleteControlDevice((WDFDEVICE)Device);
    }

    WdfCollectionRemove(DriverDeviceCollection, Device);

    WdfWaitLockRelease(DriverDeviceCollectionLock);
    TraceEvents(TRACE_LEVEL_INFORMATION, TRACE_DRIVER, "%ws %!FUNC! exit", LOG_TITLE);
    KdPrint(("%ws PnpDeviceEvtDeviceContextCleanup... exit\n", LOG_TITLE));
}

#pragma warning(pop) // enable 28118 again
